# Generated by Django 4.0 on 2022-09-21 09:00

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('email', models.CharField(blank=True, max_length=30)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('description', models.CharField(default='Napisz coś o sobie...', max_length=200)),
                ('profile_picture', models.ImageField(blank=True, default='_defaults/default_user.png', upload_to=users.models.BlogUser.user_profile_images_path)),
                ('permission_group', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
