# Generated by Django 4.0 on 2022-09-25 14:50

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to=users.models.BlogUser.user_profile_images_path),
        ),
    ]
